### ISSUE TITLE
User registration not persistent after closing Webgoat docker container

### ISSUE THREAD

**Issue by abminternet** [WebGoat/WebGoat#457]
Hi all, 

I run Webgoat8 using the following commands:
docker pull webgoat/webgoat-8.0
docker run -p 8080:8080 -it webgoat/webgoat-8.0 /home/webgoat/start.sh 

Everything seems fine, I register a new user and proceed to the lessons. If I log out, I can log in with my previously registered user. But as soon as I close the docker container and start it again, the user doesn't exist and I need to register it again. Which is very frustrating. Any ideas as to why this happens? Maybe I'm missing something?

Thx.

**Comment by nbaars** [comment]
@abminternet correct by default the image stores its data in the container, you can map the data directory to your host machine as follows:

```
docker run -p 8080:8080 -it -v /tmp/webgoat-data:/home/webgoat/.webgoat-v8.0.0.M14 webgoat/webgoat-8.0 /home/webgoat/start.sh
```

In this example `/tmp/webgoat-data` on the host will be mapped to `/home/webgoat/.webgoat-v8.0.0.M14` in the container. This way the state of the database will be saved (`/tmp/webgoat-data` can be any directory on your host)
I will add this to the documentation as well.

**Comment by nbaars** [comment]
Fixed, added to the `README.md`

**Comment by nbaars** [comment]
Thanks for reporting :+1:

**Comment by abminternet** [comment]
hi nbaars, thanks for your answer, but when I exit the container the host directory is empty and upon entering the docker container again with the command you provided, the username still doesn't exist :s

**Comment by nbaars** [comment]
@abminternet looks like something is not mapped correctly, can you try (after you start the WebGoat container):

```
docker exec -i -t CONTAINER_ID /bin/bash 
```
you can find the CONTAINER_ID with `docker ps` 

This will give you a bash shell inside the WebGoat Docker image. Can you then list the following directory: `ls -al /home/webgoat'

Just to make sure the directory on your host does exists?

**Comment by abminternet** [comment]
Hi nbaars, I did what you suggested, here is the output. It looks like there are two M14 directories with almost identical names, I tried mapping .webgoat-8.0.0.M14 instead of .webgoat-v8.0.0.M14 and now it works :D Thanks a lot!!

webgoat@9e161d208349:~$ ls -al
total 74452
drwxr-xr-x 1 webgoat webgoat     4096 May 11 13:31 .
drwxr-xr-x 1 root    root        4096 Apr 11 19:01 ..
-rw-r--r-- 1 webgoat webgoat      220 May 15  2017 .bash_logout
-rw-r--r-- 1 webgoat webgoat     3526 May 15  2017 .bashrc
-rw-r--r-- 1 webgoat webgoat      675 May 15  2017 .profile
drwxr-xr-x 2 root    root        4096 Apr 11 19:01 .webgoat
drwxr-xr-x 5 webgoat webgoat     4096 May 11 13:31 .webgoat-8.0.0.M14
drwxrwxr-x 2 webgoat webgoat     4096 May  3 19:45 .webgoat-v8.0.0.M14
-rw-rw-r-- 1 root    root    76204803 Apr 11 19:00 webgoat.jar
webgoat@9e161d208349:~$ ls -al .webgoat-*
.webgoat-8.0.0.M14:
total 24
drwxr-xr-x 5 webgoat webgoat 4096 May 11 13:31 .
drwxr-xr-x 1 webgoat webgoat 4096 May 11 13:31 ..
drwxr-xr-x 2 webgoat webgoat 4096 May 11 13:31 ClientSideFiltering
drwxr-xr-x 2 webgoat webgoat 4096 May 11 13:31 XXE
drwxr-xr-x 3 webgoat webgoat 4096 May 11 13:31 data
-rw-r--r-- 1 webgoat webgoat   45 May 11 13:31 secret.txt

.webgoat-v8.0.0.M14:
total 8
drwxrwxr-x 2 webgoat webgoat 4096 May  3 19:45 .
drwxr-xr-x 1 webgoat webgoat 4096 May 11 13:31 ..
webgoat@9e161d208349:~$

**Comment by nbaars** [comment]
Closing, as we released v8.0.0.M15

**Comment by grssnbchr** [comment]
I have the same problem but still using WebGoat 7.1. Where are the data stored, so I can map it to my host machine?
