### ISSUE TITLE
Http Basics lessons fails to load

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#53]
Due to:

```
[INFO] PARM MAP: {stage=[Ljava.lang.String;@7683034d, Screen=[Ljava.lang.String;@5e50edd8, menu=[Ljava.lang.String;@14883b86}
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key EnterYourName
[INFO] Role: user       at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
```
Did a check for the key and it is indeed missing from the WebGoat.properties. This key was available in my local workspace but after a `rm plugins_extracted` it also started failing.

**Comment by nbaars** [comment]
Fixed, used a Spring class to load the resources which cleaned up the code a lot. 
Can be closed after pull request has been merged into master

**Comment by mayhew64** [comment]
I'm still seeing the NPE with a clean build.

* Error generating org.owasp.webgoat.plugin.HttpBasics
Error Message: null
java.lang.NullPointerException
at org.owasp.webgoat.plugin.HttpBasics.createContent(HttpBasics.java:80)
at org.owasp.webgoat.lessons.AbstractLesson.handleRequest(AbstractLesson.java:737)
at org.owasp.webgoat.HammerHead.makeScreen(HammerHead.java:304)
at org.owasp.webgoat.HammerHead.doPost(HammerHead.java:152)
at org.owasp.webgoat.HammerHead.doGet(HammerHead.java:107)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)

**Comment by nbaars** [comment]
I cannot reproduce this removed the plugin_extracted directory and did a `mvn clean install` and `mvn -pl .... Tomcat7:run` The https basics lesson works.

Tested on a Linux image, cloned the container and the lessons from git, build the lessons and build the container, started up Tomcat and the http basics lesson works.

Can you send the stack trace from the console?

**Comment by mayhew64** [comment]
Tested and no NPE.
